version: '3.4'
networks: {}
volumes:
  db_volume:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_db_volume

services:
  php-fpm:
    build:
      context: php
    volumes:
      - ../web:/var/www/html
      - ${SSH_AUTH_SOCK}:/ssh-socket:ro
      - ../.composer:/var/www/.composer
    links:
      - db
      - mailhog
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      SSH_AUTH_SOCK: "/ssh-socket"
    network_mode: bridge
  cron:
    build:
      context: cron
    volumes:
      - ../web:/var/www/html
    links:
      - db
      - mailhog
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      SSH_AUTH_SOCK: "/ssh-socket"
    network_mode: bridge
  mailhog:
    image: mailhog/mailhog
    network_mode: bridge
  db:
    build:
      context: mysql
    volumes:
      - ./mysql/conf/my.cnf:/etc/my.cnf.d/development.cnf:ro
      - db_volume:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    network_mode: bridge
    ports:
      - 127.0.0.1:3306:3306
  redis:
    image: redis:alpine
    network_mode: bridge
  web:
    build:
      context: web
    volumes:
      - ../web:/var/www/html:ro
    environment:
      - MAGENTO_HOSTNAME
      - MAGENTO_ADMIN_URL
      - MAGENTO_ADMIN_USERNAME
      - MAGENTO_ADMIN_PASSWORD
      - MAGENTO_ADMIN_FIRSTNAME
      - MAGENTO_ADMIN_LASTNAME
      - MAGENTO_ADMIN_EMAIL
    links:
      - mailhog
      - php-fpm
      - rabbitmq
      - elasticsearch
      - kibana
    network_mode: bridge
  ssl:
    build:
      context: ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:backend"
    network_mode: bridge
  rabbitmq:
    build:
      context: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: bridge
  elasticsearch:
    build:
      context: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=admin
      - ELASTIC_USERNAME=admin
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
    network_mode: bridge
  kibana:
    build:
      context: kibana
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PASSWD=admin
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PORT=9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    network_mode: bridge
